// RMIT University Vietnam
//   Course: COSC2767 Systems Deployment and Operations
//   Semester: 2022B
//   Assessment: Assignment 2
//   Author: Du Duc Manh
//   ID: 3878480
//   Created  date: 15/08/2022
//   Last modified: 20/08/2022
//   Acknowledgement: Jenkins, Tomcat, Docker, Docker Hub. 


pipeline {
    agent any

    tools {
        // Install the Maven version configured as "maven" and add it to the path.
        maven "maven"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'main', url: 'https://github.com/TomHuynhSG/cosc2767-assignment2-website.git'

                // Run Maven on a Unix agent.
                sh "mvn -Dmaven.test.failure.ignore=true clean package"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }
        }
        stage('Post-build') {
            steps([$class: 'BapSshPromotionPublisherPlugin']){
                 sshPublisher(
                    continueOnError: false, failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "tomcat",
                            verbose: true,
                            transfers: [
                                sshTransfer(
                                    sourceFiles: "target/*.war",
                                    removePrefix: "target",
                                    execCommand: """
                                        cd /home/dockeradmin;
                                        docker cp *.war \$(docker ps -qf "name=tomcat"):/opt/tomcat/webapps;
                                        docker stop \$(docker ps -qf "name=tomcat")
                                        docker start tomcat
                                    """
                                )
                            ]
                        )
                    ]
                )
            }
        }
    }
}